# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Source.destroy_all
Person.destroy_all
Country.destroy_all
@sherif = Person.create!(name: "Sherif Gaber", picture: "https://assets.change.org/photos/9/qa/im/XeQaimxHZnzlkXQ-800x450-noPad.jpg?1525574336")
@raif = Person.create!(name: "Raif Badawi", picture: "https://ichef.bbci.co.uk/news/624/cpsprodpb/7D94/production/_91984123_b49301f0-1dab-4921-be9d-1f868e751ba0.jpg")
@ali = Person.create!(name: "Ali-Mohammed al-Nimr", picture: "http://ichef.bbci.co.uk/news/976/cpsprodpb/280B/production/_85815201_afp_alnimr.jpg")
@nazanin = Person.create!(name: "Nazanin Zaghari-Ratcliffe", picture: "https://ichef.bbci.co.uk/news/660/cpsprodpb/27A2/production/_100664101_2be6a96e-58a9-4cc1-866d-789b21b75f5c.jpg")
@kurdish_female_fighters = Person.create!(name: "Kurdish Female Fighters", picture: "https://cdn.cnn.com/cnnnext/dam/assets/171019142830-05-female-ypg-raqqa-avrim-difram-1-super-169.jpg")
@zelim = Person.create!(name: "Zelim Bakaev", picture: "https://queerty-prodweb.s3.amazonaws.com/2017/10/bakaev.jpg")
@assil = Person.create!(name: "Assil Belalta", picture: "https://i2.wp.com/www.towleroad.com/wp-content/uploads/2019/02/a_belalta.jpg?resize=348%2C180&ssl=1")
@channing = Person.create!(name: "Channing Smith", picture: "https://ewscripps.brightspotcdn.com/d3/b8/b27023334e1b91ea63e3c4696fe2/channingsmith.jpg")
@shatha = Person.create!(name: "Shatha Salim Bashar", picture: "https://6f86a2a761cafb234bee-915fe82910fbc36b44e130293923f848.ssl.cf2.rackcdn.com/2019/09/shatha_salim_bashar_810x540.jpg")
@omar = Person.create!(name: "Omar Alshogre", picture: "https://smp.vgc.no/v2/images/e3840506-f620-41df-b75b-58229a95fa83?fit=crop&h=1105&w=1900&s=e5a2173a5860ea4f4e7a28aa042dd2ca5ec796c7")
@mazen_mezban = Person.create!(name: "Mazen & Mezban", picture: "https://media.npr.org/assets/img/2019/03/14/img_6160-2-660070df98423b5f183d89f91bd4300e7a02e02a-s1600-c85.jpg")
@lars = Person.create!(name: "Lars Egge", picture: "https://cdn.vox-cdn.com/thumbor/JnTe43Y6HOOZ8R-r4k6MUR3s5ks=/0x442:1080x1350/1820x1213/filters:focal(345x615:517x787):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/55275819/outsports_1.0.jpg")
@jimmy_bangash = Person.create!(name: "Jimmy Bangash", picture: "https://assets.libsyn.com/secure/show/49746/jimmyBang.jpg")
@JunaidHafeez = Person.create!(name: "Junaid Hafeez", picture: "https://www.dw.com/image/50724232_303.jpg")
@yasmine = Person.create!(name: "Yasmine Mohammed", picture: "https://i.ytimg.com/vi/KTIvCx4Y1ng/maxresdefault.jpg")
Source.create!(name: "Raif Badawi Website", url: "https://www.raifbadawi.org/", person_id: @raif.id)
@raif.sources.create!(name: "Raif's Book on Amazon", url: "https://www.amazon.com/1000-Lashes-Because-What-Think/dp/1771642092")
@sherif.sources.create!(name: "Sherif Gaber Youtube Channel", url: "https://www.youtube.com/channel/UC_CKL5F9i7e9sPnZcxXP3HQ")
@ali.sources.create!(name: "Washington Post Article", url: "https://www.washingtonpost.com/news/morning-mix/wp/2015/10/07/ali-al-nimr-was-a-boy-when-thrown-in-saudi-prison-now-hes-a-man-and-is-sentenced-to-die/")
@nazanin.sources.create!(name: "The Guardian Article", url: "https://www.theguardian.com/news/2019/oct/07/nazanin-zaghari-ratcliffe-pressure-grows-on-uk-after-australians-release")
@kurdish_female_fighters.sources.create!(name: "CNN Article", url: "https://www.cnn.com/2017/10/20/middleeast/raqqa-kurdish-female-fighters/index.html")
@zelim.sources.create!(name: "Haaretz Article", url: "https://www.haaretz.com/world-news/europe/new-gay-purge-in-chechnya-kills-at-least-two-forty-detained-report-1.6834101")
@Maxim = Person.create!(name: "Maxim Lapunov", picture: "https://media2.s-nbcnews.com/j/newscms/2017_42/2192411/171017_lapunov_268036e44da071a4c22c0104d000bd76.fit-2000w.jpg")
@Maxim.sources.create!(name: "NBC Article", url: "https://www.nbcnews.com/feature/nbc-out/i-want-justice-victim-chechnya-s-hunt-gays-comes-forward-n811566")
@assil.sources.create!(name: "Daily Mail Article", url: "https://www.dailymail.co.uk/news/article-6708521/Killers-slit-students-throat-write-gay-blood-wall-Algerian-university.html")
@channing.sources.create!(name: "NBC Today Article", url: "https://www.today.com/parents/16-year-old-boy-dies-suicide-after-he-was-outed-t163564")
@shatha.sources.create!(name: "Fox News Article", url: "https://www.foxnews.com/world/yazidi-sex-slave-survivor-isis-rapist-germany")
@omar.sources.create!(name: "Omar Alshogre's Website", url: "http://www.omaralshogre.com/en-GBs")
@omar.sources.create!(name: "NPR Article", url: "https://www.npr.org/2019/09/24/754863320/how-europe-has-become-the-epicenter-for-syrian-war-crimes-cases")
@mazen_mezban.sources.create!(name: "NPR Article", url: "https://www.npr.org/2019/03/14/702650912/freed-from-isis-few-yazidis-return-to-suffering-families-many-remain-missing")
@lars.sources.create!(name: "OutSports Article", url: "https://www.outsports.com/2017/6/15/15809442/gay-suicide-bemidji-state-lars-egge")
@jimmy_bangash.sources.create!(name: "Interview with Veedu Vidz on Youtube", url: "https://www.youtube.com/watch?v=p3PJBJEC_4w")
@JunaidHafeez.sources.create!(name: "DW Article", url: "https://www.dw.com/en/junaid-hafeez-why-is-pakistani-scholars-blasphemy-case-receiving-scant-attention/a-50722310")
@yasmine.sources.create!(name: "Unveiled Lecture on Youtube", url: "https://www.youtube.com/watch?v=KTIvCx4Y1ng")
@yasmine.sources.create!(name: "Yasmine Mohammed's Book Unveiled", url: "https://www.amazon.com/dp/1999240502/ref=cm_sw_em_r_mt_dp_U_wrPQDb7G6E412")
@IlyaNohcho = Person.create!(name: "Ilya & Nohcho", picture: "https://static01.nyt.com/images/2017/04/21/world/21Chechnya1Sub/21Chechnya1Sub-superJumbo.jpg?quality=90&auto=webp")
@IlyaNohcho.sources.create!(name: "New York Times Article", url: "https://www.nytimes.com/2017/04/21/world/europe/chechnya-russia-attacks-gays.html")
@Yvette = Person.create!(name: "Yvette Cantu Schneider", picture: "https://i.ytimg.com/vi/aetCikuQhb4/maxresdefault.jpg")
@Yvette.sources.create!(name: "TWO Artcle", url: "https://truthwinsout.org/pressrelease/2019/06/41826/")
@Yvette.sources.create!(name: "GLAAD Artcle", url: "https://www.glaad.org/blog/change-possible-former-ex-gay-activist-yvette-schneider-celebrates-worthiness-and-equality-all")
@patrickmcalvey = Person.create!(name: "Patrick McAlvey", picture: "https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.mlive.com/home/mlive-media/width2048/img/lansing-news/photo/patrick-mcalveyjpg-37403812702bf9ef.jpg")
@patrickmcalvey.sources.create!(name: "ABC News Video", url: "https://abcnews.go.com/US/video/man-describes-creepy-gay-conversion-therapy-30177835")
@patrickmcalvey.sources.create!(name: "TWO Video on Youtube", url: "https://www.youtube.com/watch?v=ViaMczTmrkA")
@avinshu = Person.create!(name: "Avinshu Patel", picture: "https://theenglishpost.com/wp-content/uploads/2019/07/Gay-boy-Avinshu-Patel-commits-suicide-in-Chennai-FB_600x363.jpg")
@avinshu.sources.create!(name: "India Today Article", url: "https://www.indiatoday.in/india/story/gay-man-suicide-homophobia-lgbt-helplines-1565041-2019-07-09")
@asia = Person.create!(name: "Asia Bibi", picture: "https://a57.foxnews.com/media2.foxnews.com/BrightCove/694940094001/2018/10/31/931/524/694940094001_5855904038001_5855896431001-vs.jpg?ve=1&tl=1")
@asia.sources.create!(name: "New York Time Article", url: "https://www.nytimes.com/2019/05/08/world/asia/asia-bibi-blasphemy-pakistan-canada.html")
@Nathan_Dalley = Person.create!(name: "Nathan Dalley", picture: "https://dailyutahchronicle.com/wp-content/uploads/2019/03/IMG_1580-900x600.jpg")
@Nathan_Dalley.sources.create!(name: "Daily Utah Chronicle", url: "https://dailyutahchronicle.com/2019/04/05/he-survived-conversion-therapy-now-he-wants-to-make-sure-no-one-else-has-to/")
@shurka = Person.create!(name: "Mathew Shurka", picture: "https://img.huffingtonpost.com/asset/5bafb736250000320037f11a.jpeg?ops=scalefit_630_noupscale")
@shurka.sources.create!(name: "MTV News Article", url: "http://www.mtv.com/news/2031013/gay-conversion-therapy-dangers-matthew-shurka/")
@garrard = Person.create!(name: "Garrard Conley", picture: "https://dehayf5mhw1h7.cloudfront.net/wp-content/uploads/sites/726/2018/11/02190007/E_GarrardMarthaConley_11021-630x354.jpg")
@garrard.sources.create!(name: "NPR Article", url: "https://www.npr.org/2018/11/11/666767913/boy-erased-the-true-story-behind-the-film")
@garrard.sources.create!(name: "Boy Erased Book", url: "https://www.amazon.com/Boy-Erased-Memoir-Garrard-Conley-ebook/dp/B0141ZP3JW")
@vicky = Person.create!(name: "Vicky Beeching", picture: "https://www.gaystarnews.com/wp-content/uploads/2016/04/vicky_beeching_nicholas_dawkes.jpg")
@vicky.sources.create!(name: "Independent Article", url: "https://www.independent.co.uk/news/people/news/vicky-beeching-star-of-the-christian-rock-scene-im-gay-god-loves-me-just-the-way-i-am-9667566.html")
@vicky.sources.create!(name: "Vicky Beeching's Book", url: "https://www.amazon.com/dp/0062439901/ref=cm_sw_em_r_mt_dp_U_gaQQDbE8SBKTN")
@ali.sources.create!(name: "Amnesty International Profile", url: "https://www.amnesty.org/en/latest/campaigns/2016/02/my-heart-is-exhausted-a-mothers-story-of-death-row-in-saudi-arabia/")
