# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Source.destroy_all
Person.destroy_all
Country.destroy_all
@sherif = Person.create!(name: "Sherif Gaber", picture: "fas fa-running")
@raif = Person.create!(name: "Raif Badawi", picture: "fas fa-dungeon")
@ali = Person.create!(name: "Ali-Mohammed al-Nimr", picture: "fas fa-dungeon")
@nazanin = Person.create!(name: "Nazanin Zaghari-Ratcliffe", picture: "fas fa-dungeon")
@kurdish_female_fighters = Person.create!(name: "Kurdish Female Fighters", picture: "fas fa-fighter-jet")
@zelim = Person.create!(name: "Zelim Bakaev", picture: "fas fa-mars-double")
@assil = Person.create!(name: "Assil Belalta", picture: "fas fa-mars-double")
@channing = Person.create!(name: "Channing Smith", picture: "fas fa-mars-double")
@shatha = Person.create!(name: "Shatha Salim Bashar", picture: "fas fa-globe-europe")
@omar = Person.create!(name: "Omar Alshogre", picture: "fab fa-rebel")
@mazen_mezban = Person.create!(name: "Mazen & Mezban", picture: "fas fa-globe-europe")
@lars = Person.create!(name: "Lars Egge", picture: "fas fa-mars-double")
@jimmy_bangash = Person.create!(name: "Jimmy Bangash", picture: "fas fa-mars-double")
@JunaidHafeez = Person.create!(name: "Junaid Hafeez", picture: "fas fa-dungeon")
@yasmine = Person.create!(name: "Yasmine Mohammed", picture: "fab fa-rebel")
Source.create!(name: "Raif Badawi Website", url: "https://www.raifbadawi.org/", person_id: @raif.id)
@raif.sources.create!(name: "Raif's Book on Amazon", url: "https://www.amazon.com/1000-Lashes-Because-What-Think/dp/1771642092")
@sherif.sources.create!(name: "Sherif Gaber Youtube Channel", url: "https://www.youtube.com/channel/UC_CKL5F9i7e9sPnZcxXP3HQ")
@ali.sources.create!(name: "Washington Post Article", url: "https://www.washingtonpost.com/news/morning-mix/wp/2015/10/07/ali-al-nimr-was-a-boy-when-thrown-in-saudi-prison-now-hes-a-man-and-is-sentenced-to-die/")
@nazanin.sources.create!(name: "The Guardian Article", url: "https://www.theguardian.com/news/2019/oct/07/nazanin-zaghari-ratcliffe-pressure-grows-on-uk-after-australians-release")
@kurdish_female_fighters.sources.create!(name: "CNN Article", url: "https://www.cnn.com/2017/10/20/middleeast/raqqa-kurdish-female-fighters/index.html")
@zelim.sources.create!(name: "Haaretz Article", url: "https://www.haaretz.com/world-news/europe/new-gay-purge-in-chechnya-kills-at-least-two-forty-detained-report-1.6834101")
@Maxim = Person.create!(name: "Maxim Lapunov", picture: "fas fa-mars-double")
@Maxim.sources.create!(name: "NBC Article", url: "https://www.nbcnews.com/feature/nbc-out/i-want-justice-victim-chechnya-s-hunt-gays-comes-forward-n811566")
@assil.sources.create!(name: "Daily Mail Article", url: "https://www.dailymail.co.uk/news/article-6708521/Killers-slit-students-throat-write-gay-blood-wall-Algerian-university.html")
@channing.sources.create!(name: "NBC Today Article", url: "https://www.today.com/parents/16-year-old-boy-dies-suicide-after-he-was-outed-t163564")
@shatha.sources.create!(name: "Fox News Article", url: "https://www.foxnews.com/world/yazidi-sex-slave-survivor-isis-rapist-germany")
@omar.sources.create!(name: "Omar Alshogre's Website", url: "http://www.omaralshogre.com/en-GBs")
@omar.sources.create!(name: "NPR Article", url: "https://www.npr.org/2019/09/24/754863320/how-europe-has-become-the-epicenter-for-syrian-war-crimes-cases")
@mazen_mezban.sources.create!(name: "NPR Article", url: "https://www.npr.org/2019/03/14/702650912/freed-from-isis-few-yazidis-return-to-suffering-families-many-remain-missing")
@lars.sources.create!(name: "OutSports Article", url: "https://www.outsports.com/2017/6/15/15809442/gay-suicide-bemidji-state-lars-egge")
@jimmy_bangash.sources.create!(name: "Interview with Veedu Vidz on Youtube", url: "https://www.youtube.com/watch?v=p3PJBJEC_4w")
@JunaidHafeez.sources.create!(name: "DW Article", url: "https://www.dw.com/en/junaid-hafeez-why-is-pakistani-scholars-blasphemy-case-receiving-scant-attention/a-50722310")
@yasmine.sources.create!(name: "Unveiled Lecture on Youtube", url: "https://www.youtube.com/watch?v=KTIvCx4Y1ng")
@yasmine.sources.create!(name: "Yasmine Mohammed's Book Unveiled", url: "https://www.amazon.com/dp/1999240502/ref=cm_sw_em_r_mt_dp_U_wrPQDb7G6E412")
@IlyaNohcho = Person.create!(name: "Ilya & Nohcho", picture: "fas fa-mars-double")
@IlyaNohcho.sources.create!(name: "New York Times Article", url: "https://www.nytimes.com/2017/04/21/world/europe/chechnya-russia-attacks-gays.html")
@Yvette = Person.create!(name: "Yvette Cantu Schneider", picture: "fas fa-venus-double")
@Yvette.sources.create!(name: "TWO Artcle", url: "https://truthwinsout.org/pressrelease/2019/06/41826/")
@Yvette.sources.create!(name: "GLAAD Artcle", url: "https://www.glaad.org/blog/change-possible-former-ex-gay-activist-yvette-schneider-celebrates-worthiness-and-equality-all")
@patrickmcalvey = Person.create!(name: "Patrick McAlvey", picture: "fas fa-mars-double")
@patrickmcalvey.sources.create!(name: "ABC News Video", url: "https://abcnews.go.com/US/video/man-describes-creepy-gay-conversion-therapy-30177835")
@patrickmcalvey.sources.create!(name: "TWO Video on Youtube", url: "https://www.youtube.com/watch?v=ViaMczTmrkA")
@avinshu = Person.create!(name: "Avinshu Patel", picture: "fas fa-mars-double")
@avinshu.sources.create!(name: "India Today Article", url: "https://www.indiatoday.in/india/story/gay-man-suicide-homophobia-lgbt-helplines-1565041-2019-07-09")
@asia = Person.create!(name: "Asia Bibi", picture: "fas fa-bible")
@asia.sources.create!(name: "New York Time Article", url: "https://www.nytimes.com/2019/05/08/world/asia/asia-bibi-blasphemy-pakistan-canada.html")
@Nathan_Dalley = Person.create!(name: "Nathan Dalley", picture: "fas fa-mars-double")
@Nathan_Dalley.sources.create!(name: "Daily Utah Chronicle", url: "https://dailyutahchronicle.com/2019/04/05/he-survived-conversion-therapy-now-he-wants-to-make-sure-no-one-else-has-to/")
@shurka = Person.create!(name: "Mathew Shurka", picture: "fas fa-mars-double")
@shurka.sources.create!(name: "MTV News Article", url: "http://www.mtv.com/news/2031013/gay-conversion-therapy-dangers-matthew-shurka/")
@garrard = Person.create!(name: "Garrard Conley", picture: "fas fa-mars-double")
@garrard.sources.create!(name: "NPR Article", url: "https://www.npr.org/2018/11/11/666767913/boy-erased-the-true-story-behind-the-film")
@garrard.sources.create!(name: "Boy Erased Book", url: "https://www.amazon.com/Boy-Erased-Memoir-Garrard-Conley-ebook/dp/B0141ZP3JW")
@vicky = Person.create!(name: "Vicky Beeching", picture: "fas fa-venus-double")
@vicky.sources.create!(name: "Independent Article", url: "https://www.independent.co.uk/news/people/news/vicky-beeching-star-of-the-christian-rock-scene-im-gay-god-loves-me-just-the-way-i-am-9667566.html")
@vicky.sources.create!(name: "Vicky Beeching's Book", url: "https://www.amazon.com/dp/0062439901/ref=cm_sw_em_r_mt_dp_U_gaQQDbE8SBKTN")
@ali.sources.create!(name: "Amnesty International Profile", url: "https://www.amnesty.org/en/latest/campaigns/2016/02/my-heart-is-exhausted-a-mothers-story-of-death-row-in-saudi-arabia/")
